const AUTH_SUCCESSFUL = 'AUTH_SUCCESSFUL';
const AUTH_FAILURE = 'AUTH_FAILURE';
const AUTH_REQUEST = 'AUTH_REQUEST';
const LOG_OUT = 'LOG_OUT';
const UPDATE_DATA_SUCCESSFUL = 'UPDATE_DATA_SUCCESSFUL';
const UPDATE_DATA_FAILURE = 'UPDATE_DATA_FAILURE';
const UPDATE_DATA_REQUEST = 'UPDATE_DATA_REQUEST';
const FETCH_USER_BACKGROUND = 'FETCH_USER_BACKGROUND';
const USER_BACKGROUND_FETCHED = 'USER_BACKGROUND_FETCHED';


const REGISTRATION_SUCCESSFUL = 'REGISTRATION_SUCCESSFUL';
const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE';
const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';




export {
    AUTH_SUCCESSFUL,
    AUTH_FAILURE,
    AUTH_REQUEST,
    LOG_OUT,
    REGISTRATION_SUCCESSFUL,
    REGISTRATION_FAILURE,
    REGISTRATION_REQUEST,
    UPDATE_DATA_SUCCESSFUL,
    UPDATE_DATA_FAILURE,
    UPDATE_DATA_REQUEST,
    FETCH_USER_BACKGROUND,
    USER_BACKGROUND_FETCHED
};